baseURL = "https://dedov.ws/"
languageCode = "ru"
title = "My HUGO Website"
languageName = 'Russian'
defaultContentLanguage = "ru"
paginate = 100 #frontpage pagination
enableGitInfo = true

# theme = "PaperMod"
# theme = "ananke"
# theme = "monochrome"
theme = "LoveIt"

# Author config
[author]
  name = "Sergey Dedov"
  email = "sergey@dedov.ws"
  link = "https://dedov.ws"

[params]
    description = "My personal web site"
    navbar_title = "Sergey DEDOV" # default: site's `title`
    footer = "Copyright © 2023 by OkulusDev" # default: None
    enable_toc = true # default: true
    enable_collapsible_toc = true # default: false
    enable_collapsible_changelogs = false # default: false
    enable_math = true
    enable_site_search = true # default: false
    color_scheme = "dark" # "light" or "dark"

    [params.list_layout]
        enable_group_by_year = false # default: true
        enable_show_date = true # default: true
        enable_pagination = true # default: false


# Местоположение контента, шаблонов и т. д.
contentDir = "content"
layoutDir = "layouts"
staticDir= "static"

# Настройки развертывания (deployment)
disableKinds = []
canonifyURLs= true
uglyURLs=false

[taxonomies]
  tag="tags"
  category="categories"

[[menu.main]]
    name= "Домой"
    url="/"
    weight=1

[[menu.main]]
    name="Статьи"
    url="/articles/"
    weight=2

[[menu.main]]
    name="Обо мне"
    url="/about/"
    weight=3

[[menu.main]]
    identifier = "tags"
    name = "Теги"
    url = "/tags/"
    weight = 4

[[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/post/"
    weight = 5

[[menu.main]]
    identifier = "categories"
    name = "Категории"
    url = "/categories/"
    weight = 6